--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/lake/wallpapers/walls/ashim-d-silva-WeYamle9fDM-unsplash.jpg"

-- Special
background="#110a19"
foreground="#c3c1c5"
cursor="#c3c1c5"

-- Colors
color0="#110a19"
color1="#9f4e21"
color2="#764243"
color3="#99553f"
color4="#b0632c"
color5="#ad6a47"
color6="#6f5168"
color7="#928e98"
color8="#63596e"
color9="#D5682D"
color10="#9E585A"
color11="#CC7255"
color12="#EB843B"
color13="#E78E5F"
color14="#946D8B"
color15="#c3c1c5"
