--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/lake/Dotfiles/wallpapers/pywallpaper.jpg"

-- Special
background="#021E25"
foreground="#adc2b8"
cursor="#adc2b8"

-- Colors
color0="#021E25"
color1="#B26E4E"
color2="#2F8379"
color3="#608A7A"
color4="#AA9473"
color5="#FA8F44"
color6="#E5965F"
color7="#adc2b8"
color8="#798780"
color9="#B26E4E"
color10="#2F8379"
color11="#608A7A"
color12="#AA9473"
color13="#FA8F44"
color14="#E5965F"
color15="#adc2b8"
